#!/bin/bash 
html=$(wget -qO- $1)
count=$(echo $html | grep -oE totalSlides\":[0-9]+ | grep -oE [0-9]+)
urlFirst="http:"$(echo $html | grep -Po pin_image_url\":\".+?\.jpg | grep -Po //.+)
#echo $urlFirst
for i in $(seq $count); do wget $(echo $urlFirst | sed s/slide-1/slide-$i/g) -O $i.jpg; done
convert %d.jpg[1-$count] $2